### ISSUE TITLE
setText using non-ASCII text would throw exception when using node 6.0.0 and appium 1.5.3

### ISSUE THREAD

**Issue by truebit** [appium/appium-selendroid-driver#25]
> 2016-06-15 11:54:06:131 - [HTTP] <-- POST /wd/hub/session/4c7c5de2-76c8-417d-9034-72303ed7da5b/timeouts 200 14 ms - 63 
> 2016-06-15 11:54:06:134 - [HTTP] --> POST /wd/hub/session/4c7c5de2-76c8-417d-9034-72303ed7da5b/element/914830c5-95d8-1f78-e2bf-f3b6f54e267a/value {"id":"914830c5-95d8-1f78-e2bf-f3b6f54e267a","value":["你好"]}
> 2016-06-15 11:54:06:134 - [MJSONWP] Calling AppiumDriver.setValue() with args: [["你好"],"914830c5-95d8-1f78...
> 2016-06-15 11:54:06:135 - [debug] [Selendroid] Setting text on element '914830c5-95d8-1f78-e2bf-f3b6f54e267a': '你好'
> **2016-06-15 11:54:06:165 - [MJSONWP] Encountered internal error running command: Error: If encoding is specified then the first argument must be a string**
>     at new Buffer (buffer.js:106:13)
>     at encode (/usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/node_modules/utf7/utf7.js:4:13)
>     at /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/node_modules/utf7/utf7.js:77:39
>     at RegExp.[Symbol.replace](native)
>     at String.replace (native)
>     at Object.exports.imap.encode (/usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/node_modules/utf7/utf7.js:75:36)
>     at encodeString (lib/commands.js:47:22)
>     at SelendroidDriver.callee$0$0$ (lib/commands.js:61:11)
>     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke](/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next](/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
>     at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
>     at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
>     at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.export.js:30:36)
>     at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
>     at AsyncIterator.prototype.(anonymous function) [as next](/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
>     at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
>     at SelendroidDriver.callee$0$0 [as setValue](lib/commands.js:56:53)
>     at lib/basedriver/driver.js:163:24
>     at tryCatcher (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/util.js:26:23)
>     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:507:31)
>     at Promise._settlePromiseAt (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:581:18)
>     at Promise._settlePromiseAtPostResolution (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:245:10)
>     at Async._drainQueue (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:128:12)
>     at Async._drainQueues (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:133:10)
>     at Immediate.Async.drainQueues [as _onImmediate](/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:15:14)
>     at tryOnImmediate (timers.js:543:15)
>     at processImmediate [as _immediateCallback](timers.js:523:5)

**Comment by truebit** [comment]
This is a bug in `utf7` node module with node version >=6.0.  you could reproduce it simply using node REPL:
$node
> var utf7=require('utf7').imap;
undefined
> utf7.encode('你好')
Error: If encoding is specified then the first argument must be a string
    at new Buffer (buffer.js:106:13)
    at encode (/usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/node_modules/utf7/utf7.js:4:13)
    at /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/node_modules/utf7/utf7.js:77:39
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at Object.exports.imap.encode (/usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/node_modules/utf7/utf7.js:75:36)
    at repl:1:3
    at REPLServer.defaultEval (repl.js:272:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
>

**Comment by truebit** [comment]
I have reported to https://github.com/kkaefer/utf7/issues/3
Need `utf7` bugfix
