### ISSUE TITLE
failed npm install -g appium

### ISSUE THREAD

**Issue by nitinashish** [appium/appium-selendroid-driver#37]
Install info:
node -v : v6.6.0
npm -v : 3.10.7

Fails with following trace
> appium-chromedriver@2.9.2 install /Users/<user>/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver
> node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.21' for platform 'mac' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_mac32 to...
info Chromedriver Install Downloading http://chromedriver.storage.googleapis.com/2.21/chromedriver_mac32.zip...
info Chromedriver Install Writing binary content to /var/folders/nt/p_g2xxn52pqg88p_f1k518_m0000gn/T/2016828-8526-16zx1hw.0xypn9udi/chromedriver_mac32.zip...
info Chromedriver Install Extracting /var/folders/nt/p_g2xxn52pqg88p_f1k518_m0000gn/T/2016828-8526-16zx1hw.0xypn9udi/chromedriver_mac32.zip to /var/folders/nt/p_g2xxn52pqg88p_f1k518_m0000gn/T/2016828-8526-16zx1hw.0xypn9udi/chromedriver_mac32
info Chromedriver Install Creating /Users/<user>/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac...
info Chromedriver Install Copying unzipped binary, reading from /var/folders/nt/p_g2xxn52pqg88p_f1k518_m0000gn/T/2016828-8526-16zx1hw.0xypn9udi/chromedriver_mac32/chromedriver...
info Chromedriver Install Writing to /Users/<user>/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver...
info Chromedriver Install /Users/<user>/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver successfully put in place

> appium-selendroid-driver@1.3.4 install /Users/<user>/node_modules/appium/node_modules/appium-selendroid-driver
> node ./bin/install.js

dbug AndroidDriver Getting Java version
info SelendroidInstaller Ensuring /Users/<user>/node_modules/appium/node_modules/appium-selendroid-driver/node_modules/appium-selendroid-installer/selendroid/download exists
info SelendroidInstaller Downloading Selendroid standalone server version 0.17.0 from https://github.com/selendroid/selendroid/releases/download/0.17.0/selendroid-standalone-0.17.0-with-dependencies.jar --> /Users/<user>/node_modules/appium/node_modules/appium-selendroid-driver/node_modules/appium-selendroid-installer/selendroid/download/selendroid-server.jar

lib/teen_process.js:65
        let err = new Error(`Command '${rep}' exited with code ${code}`);
                  ^
Error: Command 'java -version' exited with code 20
    at ChildProcess.<anonymous> (lib/teen_process.js:65:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
/Users/nitinashish
└─┬ fsevents@1.0.14 
  ├── nan@2.4.0 
  └─┬ node-pre-gyp@0.6.29 
    ├─┬ mkdirp@0.5.1 
    │ └── minimist@0.0.8 
    ├─┬ nopt@3.0.6 
    │ └── abbrev@1.0.9 
    ├─┬ npmlog@3.1.2 
    │ ├─┬ are-we-there-yet@1.1.2 
    │ │ └── delegates@1.0.0 
    │ ├── console-control-strings@1.1.0 
    │ ├─┬ gauge@2.6.0 
    │ │ ├── aproba@1.0.4 
    │ │ ├── has-color@0.1.7 
    │ │ ├── has-unicode@2.0.1 
    │ │ ├── object-assign@4.1.0 
    │ │ ├── signal-exit@3.0.0 
    │ │ ├─┬ string-width@1.0.1 
    │ │ │ ├─┬ code-point-at@1.0.0 
    │ │ │ │ └── number-is-nan@1.0.0 
    │ │ │ └── is-fullwidth-code-point@1.0.0 
    │ │ ├─┬ strip-ansi@3.0.1 
    │ │ │ └── ansi-regex@2.0.0 
    │ │ └── wide-align@1.1.0 
    │ └── set-blocking@2.0.0 
    ├─┬ rc@1.1.6 
    │ ├── deep-extend@0.4.1 
    │ ├── ini@1.3.4 
    │ ├── minimist@1.2.0 
    │ └── strip-json-comments@1.0.4 
    ├─┬ request@2.73.0 
    │ ├── aws-sign2@0.6.0 
    │ ├── aws4@1.4.1 
    │ ├─┬ bl@1.1.2 
    │ │ └── readable-stream@2.0.6 
    │ ├── caseless@0.11.0 
    │ ├─┬ combined-stream@1.0.5 
    │ │ └── delayed-stream@1.0.0 
    │ ├── extend@3.0.0 
    │ ├── forever-agent@0.6.1 
    │ ├─┬ form-data@1.0.0-rc4 
    │ │ └── async@1.5.2 
    │ ├─┬ har-validator@2.0.6 
    │ │ ├─┬ chalk@1.1.3 
    │ │ │ ├── ansi-styles@2.2.1 
    │ │ │ ├── escape-string-regexp@1.0.5 
    │ │ │ ├── has-ansi@2.0.0 
    │ │ │ └── supports-color@2.0.0 
    │ │ ├─┬ commander@2.9.0 
    │ │ │ └── graceful-readlink@1.0.1 
    │ │ ├─┬ is-my-json-valid@2.13.1 
    │ │ │ ├── generate-function@2.0.0 
    │ │ │ ├─┬ generate-object-property@1.2.0 
    │ │ │ │ └── is-property@1.0.2 
    │ │ │ ├── jsonpointer@2.0.0 
    │ │ │ └── xtend@4.0.1 
    │ │ └─┬ pinkie-promise@2.0.1 
    │ │   └── pinkie@2.0.4 
    │ ├─┬ hawk@3.1.3 
    │ │ ├── boom@2.10.1 
    │ │ ├── cryptiles@2.0.5 
    │ │ ├── hoek@2.16.3 
    │ │ └── sntp@1.0.9 
    │ ├─┬ http-signature@1.1.1 
    │ │ ├── assert-plus@0.2.0 
    │ │ ├─┬ jsprim@1.3.0 
    │ │ │ ├── extsprintf@1.0.2 
    │ │ │ ├── json-schema@0.2.2 
    │ │ │ └── verror@1.3.6 
    │ │ └─┬ sshpk@1.8.3 
    │ │   ├── asn1@0.2.3 
    │ │   ├── assert-plus@1.0.0 
    │ │   ├─┬ dashdash@1.14.0 
    │ │   │ └── assert-plus@1.0.0 
    │ │   ├── ecc-jsbn@0.1.1 
    │ │   ├─┬ getpass@0.1.6 
    │ │   │ └── assert-plus@1.0.0 
    │ │   ├── jodid25519@1.0.2 
    │ │   ├── jsbn@0.1.0 
    │ │   └── tweetnacl@0.13.3 
    │ ├── is-typedarray@1.0.0 
    │ ├── isstream@0.1.2 
    │ ├── json-stringify-safe@5.0.1 
    │ ├─┬ mime-types@2.1.11 
    │ │ └── mime-db@1.23.0 
    │ ├── node-uuid@1.4.7 
    │ ├── oauth-sign@0.8.2 
    │ ├── qs@6.2.0 
    │ ├── stringstream@0.0.5 
    │ ├── tough-cookie@2.2.2 
    │ └── tunnel-agent@0.4.3 
    ├─┬ rimraf@2.5.3 
    │ └─┬ glob@7.0.5 
    │   ├── fs.realpath@1.0.0 
    │   ├── inflight@1.0.5 
    │   ├─┬ minimatch@3.0.2 
    │   │ └─┬ brace-expansion@1.1.5 
    │   │   ├── balanced-match@0.4.2 
    │   │   └── concat-map@0.0.1 
    │   └── path-is-absolute@1.0.0 
    ├── semver@5.2.0 
    ├─┬ tar@2.2.1 
    │ ├── block-stream@0.0.9 
    │ ├─┬ fstream@1.0.10 
    │ │ └── graceful-fs@4.1.4 
    │ └── inherits@2.0.1 
    └─┬ tar-pack@3.1.4 
      ├─┬ debug@2.2.0 
      │ └── ms@0.7.1 
      ├── fstream-ignore@1.0.5 
      ├─┬ once@1.3.3 
      │ └── wrappy@1.0.2 
      ├─┬ readable-stream@2.1.4 
      │ ├── buffer-shims@1.0.0 
      │ ├── core-util-is@1.0.2 
      │ ├── isarray@1.0.0 
      │ ├── process-nextick-args@1.0.7 
      │ ├── string_decoder@0.10.31 
      │ └── util-deprecate@1.0.2 
      └── uid-number@0.0.6 

npm WARN enoent ENOENT: no such file or directory, open '/Users/<user>/package.json'
npm WARN <user> No description
npm WARN <user> No repository field.
npm WARN <user> No README data
npm WARN <user> No license field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.6.0/bin/node" "/usr/local/bin/npm" "install" "appium"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE

npm ERR! appium-selendroid-driver@1.3.4 install: `node ./bin/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-selendroid-driver@1.3.4 install script 'node ./bin/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-selendroid-driver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-selendroid-driver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-selendroid-driver
npm ERR! There is likely additional logging output above.

**Comment by nitinashish** [comment]
Installed successfully when logged in as ROOT
